import {useCallback,useEffect,useMemo,useState} from 'react';
import ReactFlow,{Background,Controls,MarkerType,MiniMap,Node,Edge} from 'reactflow';
import 'reactflow/dist/style.css';
import {api} from '../lib/api';
import {OverviewTreeData,Quarter,User} from '../types/api';
import {QuarterBadge} from '../components/Badges';

function currentYearQuarter(){const now=new Date();return{year:now.getFullYear(),quarter:Math.floor(now.getMonth()/3)+1}}
function isCurrentOrFuture(q:Quarter){const c=currentYearQuarter();return q.year>c.year||(q.year===c.year&&q.quarter>=c.quarter)}
function quarterStatusLabel(q:Quarter){if(q.is_completed)return 'completed';if(q.is_active)return 'active';return q.status==='published'?'generated':q.status}
function quarterStatusClass(status:string){return status==='published'?'border-green-400/50 bg-green-500/10 text-green-200':status==='completed'?'border-slate-500 bg-slate-500/10 text-slate-300':'border-border bg-black/20 text-slate-300'}

export function Dashboard({user}:{user:User}){
 const [data,setData]=useState<OverviewTreeData|null>(null);const[quarters,setQuarters]=useState<Quarter[]>([]);const[selectedQuarterId,setSelectedQuarterId]=useState<string>('active');const[error,setError]=useState('');
 const loadTree=useCallback((id:string)=>{setError('');const path=id==='active'?'/quarters/active/overview-tree':`/quarters/${id}/overview-tree`;api<OverviewTreeData>(path).then(setData).catch(e=>setError(e.message))},[]);
 useEffect(()=>{loadTree(selectedQuarterId)},[selectedQuarterId,loadTree]);
 useEffect(()=>{if(user.is_admin)api<Quarter[]>('/quarters?include_history=true').then(setQuarters).catch(()=>{})},[user.is_admin]);
 const selectable=useMemo(()=>quarters.filter(isCurrentOrFuture).sort((a,b)=>a.year-b.year||a.quarter-b.quarter),[quarters]);
 const schedule=useMemo(()=>{const y=currentYearQuarter().year;return[1,2,3,4].map(q=>quarters.find(row=>row.year===y&&row.quarter===q)||null)},[quarters]);
 if(error)return <div className="card p-6 text-red-300">{error}</div>;
 return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-semibold tracking-tight">Dashboard</h1><p className="mt-1 text-slate-400">Visual overview of the selected quarter's giving tree.</p></div><QuarterBadge label={data?.quarter?.label}/></div>
  {user.is_admin&&<div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_420px]"><div className="card p-4"><label className="text-sm font-semibold text-slate-200">View quarter tree</label><p className="mt-1 text-sm text-slate-400">This only changes the dashboard preview. Public links still follow the live calendar quarter.</p><select value={selectedQuarterId} onChange={e=>setSelectedQuarterId(e.target.value)} className="mt-3 w-full rounded bg-bg p-3"><option value="active">Current live quarter</option>{selectable.map(q=><option key={q.id} value={q.id}>{q.label} — {quarterStatusLabel(q)}</option>)}</select></div><YearSchedule quarters={schedule}/></div>}
  {!data?<div className="card p-6 text-slate-400">Loading quarter tree…</div>:<QuarterTreeOverview data={data}/>} 
 </div>
}

function YearSchedule({quarters}:{quarters:(Quarter|null)[]}){const y=currentYearQuarter().year;return <div className="card p-4"><h2 className="font-semibold">{y} quarters</h2><p className="mt-1 text-sm text-slate-400">Quick check of which quarters have been generated for this year.</p><div className="mt-4 grid grid-cols-2 gap-3">{quarters.map((q,i)=><div key={i} className={`rounded-xl border p-3 ${q?quarterStatusClass(q.status):'border-border bg-black/10 text-slate-400'}`}><div className="text-xs uppercase tracking-wide">Q{i+1}</div><div className="mt-1 font-semibold">{q?q.label:'Not generated'}</div><div className="mt-1 text-xs">{q?quarterStatusLabel(q):'missing'}</div></div>)}</div></div>}

function QuarterTreeOverview({data}:{data:OverviewTreeData}){const built=useMemo(()=>buildQuarterTree(data),[data]);const total=data.allocations.reduce((s,a)=>s+a.points,0);return <div className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><div className="card p-4"><p className="text-xs text-slate-400">Quarter</p><p className="text-2xl font-semibold">{data.quarter?.label||'None'}</p></div><div className="card p-4"><p className="text-xs text-slate-400">Participants</p><p className="text-2xl font-semibold">{data.users.length}</p></div><div className="card p-4"><p className="text-xs text-slate-400">Allocated points</p><p className="text-2xl font-semibold">{total}</p></div></div>{!data.quarter?<div className="card p-8 text-center text-slate-400">No live quarter is currently available. Admins can use the selector above to preview generated future quarters.</div>:<div className="h-[680px] overflow-hidden rounded-2xl border border-border bg-[#0d0f1a]"><ReactFlow nodes={built.nodes} edges={built.edges} fitView fitViewOptions={{padding:.22}} minZoom={0.2}><Background color="#2a2d3e"/><MiniMap style={{background:'#0d0f1a',border:'1px solid #2a2d3e'}}/><Controls/></ReactFlow></div>}</div>}

function buildQuarterTree(data:OverviewTreeData):{nodes:Node[];edges:Edge[]}{const users=[...data.users].sort((a,b)=>a.display_name.localeCompare(b.display_name));const radius=Math.max(260,users.length*42);const cx=radius+220,cy=radius+160;const nodes:Node[]=users.map((u,i)=>{const angle=(2*Math.PI*i)/Math.max(1,users.length)-Math.PI/2;return{id:`p-${u.member_id}`,position:{x:cx+radius*Math.cos(angle),y:cy+radius*Math.sin(angle)},data:{label:<div className="text-center"><div className="font-bold">{u.display_name}</div><div className="text-[10px] text-slate-300">gives {u.total_points_sent} · receives {u.total_points_received}</div><div className="text-[10px] text-slate-400">to {u.recipient_count} · from {u.incoming_allocation_count}</div></div>},style:{background:'#111827',border:'2px solid #6366f1',borderRadius:16,color:'#f8fafc',padding:'10px 12px',minWidth:145,textAlign:'center'}}});
 const edgeMap=new Map<string,{points:number;ack:boolean}>();for(const a of data.allocations){const key=`${a.source_member_id}-${a.recipient_member_id}`;const prev=edgeMap.get(key)||{points:0,ack:true};edgeMap.set(key,{points:prev.points+a.points,ack:prev.ack&&a.acknowledged})}
 const edges:Edge[]=Array.from(edgeMap.entries()).map(([key,val])=>{const [source,target]=key.split('-');return{id:`e-${key}`,source:`p-${source}`,target:`p-${target}`,label:`${val.points}`,animated:!val.ack,markerEnd:{type:MarkerType.ArrowClosed},style:{stroke:val.ack?'#22c55e':'#f59e0b',strokeWidth:2},labelStyle:{fill:'#e2e8f0',fontSize:12},labelBgStyle:{fill:'#0f172a',fillOpacity:.9}}});return{nodes,edges}}
