import {useEffect,useMemo,useState} from 'react';
import {CompatibilityRule,Participant} from '../types/api';
import {api,del,patch,post} from '../lib/api';

export function Participants(){
  return <div className="space-y-6">
    <div>
      <h1 className="text-3xl font-semibold">Participants</h1>
      <p className="mt-1 text-slate-400">Manage distribution participants and their compatibility grid.</p>
    </div>
    <ParticipantManagement/>
    <CompatibilityGrid/>
  </div>;
}

function ParticipantManagement(){
 const[items,setItems]=useState<Participant[]>([]);const[search,setSearch]=useState('');const[filter,setFilter]=useState('all');const[name,setName]=useState('');const[bulk,setBulk]=useState('');const[msg,setMsg]=useState('');const[edit,setEdit]=useState<Record<number,Partial<Participant>>>({});
 const load=async()=>setItems(await api<Participant[]>(`/participants?include_inactive=true${search?`&search=${encodeURIComponent(search)}`:''}`));useEffect(()=>{void load()},[search]);
 const visible=items.filter(p=>filter==='all'||(filter==='active'?p.is_active:!p.is_active));
 async function add(e:React.FormEvent){e.preventDefault();try{await post('/participants',{display_name:name});setName('');setMsg('Participant created.');await load()}catch(e:any){setMsg(e.message)}}
 async function addBulk(){try{const r=await post<any>('/participants/bulk',{names:bulk});setMsg(r.message||`${r.created_count||0} participants created`);if((r.created_count||0)>0)setBulk('');await load()}catch(e:any){setMsg(e.message)}}
 async function save(p:Participant){try{await patch(`/participants/${p.id}`,edit[p.id]||{});setEdit(e=>{const n={...e};delete n[p.id];return n});setMsg('Participant updated.');await load()}catch(e:any){setMsg(e.message)}}
 async function toggle(p:Participant){try{await (p.is_active?post(`/participants/${p.id}/deactivate`):post(`/participants/${p.id}/reactivate`));await load()}catch(e:any){setMsg(e.message)}}
 async function remove(p:Participant){if(!confirm(`Delete ${p.display_name}? Historical participants cannot be deleted and should be deactivated instead.`))return;try{await del(`/participants/${p.id}`);await load()}catch(e:any){setMsg(e.message)}}
 const val=(p:Participant,k:keyof Participant)=>String((edit[p.id]?.[k]??p[k]??''));
 return <div className="space-y-4"><div className="card p-6"><h2 className="text-lg font-semibold">Participant Management</h2><p className="mt-1 text-sm text-slate-400">Participants are distribution people only. No username, password, email or role is required.</p><form onSubmit={add} className="mt-4 flex gap-2"><input value={name} onChange={e=>setName(e.target.value)} required placeholder="Participant name" className="flex-1 rounded bg-bg p-3 text-sm"/><button className="rounded bg-indigo-500 px-4 font-semibold">Add participant</button></form><div className="mt-4 grid gap-3 md:grid-cols-[1fr_auto]"><textarea value={bulk} onChange={e=>setBulk(e.target.value)} placeholder={'Paste names, one per line\nAdam\nAlex\nBilly'} className="min-h-32 rounded bg-bg p-3 text-sm"/><button onClick={addBulk} disabled={!bulk.trim()} className="rounded bg-teal-500 px-4 font-semibold disabled:opacity-50">Bulk add</button></div>{msg&&<p className="mt-3 rounded bg-black/20 p-3 text-sm text-slate-200">{msg}</p>}</div><div className="card p-6"><div className="flex flex-wrap gap-2"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search participants" className="rounded bg-bg p-3 text-sm"/><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded bg-bg p-3 text-sm"><option value="all">All</option><option value="active">Active</option><option value="inactive">Inactive</option></select><span className="p-3 text-sm text-slate-400">{visible.length} shown / {items.length} total</span></div><div className="mt-4 overflow-auto"><table className="w-full text-sm"><thead className="text-left text-slate-400"><tr><th className="p-2">Name</th><th>Slug</th><th>Status</th><th>Current quarter</th><th>Public link</th><th/></tr></thead><tbody>{visible.map(p=><tr key={p.id} className="border-t border-border"><td className="p-2"><input value={val(p,'display_name')} onChange={e=>setEdit({...edit,[p.id]:{...edit[p.id],display_name:e.target.value}})} className="rounded bg-bg p-2"/></td><td><input value={val(p,'slug')} onChange={e=>setEdit({...edit,[p.id]:{...edit[p.id],slug:e.target.value}})} className="rounded bg-bg p-2"/></td><td>{p.is_active?'Active':'Inactive'}</td><td>{p.included_in_current_quarter?'Included':'Not included'}</td><td><a className="text-indigo-300 underline" href={`/tree/${p.slug}`} target="_blank">/tree/{p.slug}</a> <button onClick={()=>navigator.clipboard?.writeText(`${location.origin}/tree/${p.slug}`)} className="ml-2 rounded border border-border px-2 py-1 text-xs">Copy</button></td><td className="space-x-2 whitespace-nowrap"><button onClick={()=>save(p)} className="rounded bg-indigo-500 px-3 py-1 text-xs">Save</button><button onClick={()=>toggle(p)} className="rounded border border-border px-3 py-1 text-xs">{p.is_active?'Deactivate':'Reactivate'}</button><button onClick={()=>remove(p)} className="rounded border border-red-400 px-3 py-1 text-xs text-red-200">Delete</button></td></tr>)}</tbody></table></div></div></div>
}

function CompatibilityGrid(){const[participants,setParticipants]=useState<Participant[]>([]);const[rules,setRules]=useState<CompatibilityRule[]>([]);const[sel,setSel]=useState<number[]>([]);const[msg,setMsg]=useState('');const load=async()=>{setParticipants(await api<Participant[]>('/participants?include_inactive=false'));setRules(await api<CompatibilityRule[]>('/compatibility/rules'))};useEffect(()=>{void load()},[]);const map=useMemo(()=>new Map(rules.map(r=>[`${r.from_participant_id}:${r.to_participant_id}`,r.is_allowed])),[rules]);async function setRule(a:number,b:number,allowed:boolean){await api('/compatibility/rules',{method:'PUT',body:JSON.stringify({from_participant_id:a,to_participant_id:b,is_allowed:allowed,mutual:false})});await load()}async function bulk(path:string){await post(`/compatibility/${path}`,{from_participant_ids:sel,to_participant_ids:sel,is_allowed:path==='bulk-allow',mutual:true});setMsg(path==='bulk-allow'?'Selected group allowed.':'Selected group blocked.');await load()}return <div className="card overflow-auto p-6"><h2 className="text-lg font-semibold">Compatibility</h2><p className="mt-1 text-sm text-slate-400">Click cells to allow or block directed relationships. The grid makes it clear which row participant can give to which column participant.</p>{msg&&<p className="mt-3 text-sm text-slate-300">{msg}</p>}<div className="my-4 flex flex-wrap gap-2">{participants.map(p=><label key={p.id} className="rounded border border-border px-3 py-1 text-sm"><input type="checkbox" checked={sel.includes(p.id)} onChange={e=>setSel(e.target.checked?[...sel,p.id]:sel.filter(id=>id!==p.id))}/> {p.display_name}</label>)}<button onClick={()=>bulk('bulk-allow')} disabled={sel.length<2} className="rounded bg-teal-500 px-3 text-sm font-semibold disabled:opacity-50">Allow selected group</button><button onClick={()=>bulk('bulk-block')} disabled={sel.length<2} className="rounded border border-red-400 px-3 text-sm font-semibold text-red-200 disabled:opacity-50">Block selected group</button></div><table className="min-w-full border-collapse text-xs"><thead><tr><th className="sticky left-0 top-0 z-20 border border-border bg-card p-2 text-left">Row participant gives to →</th>{participants.map(p=><th key={p.id} className="sticky top-0 z-10 border border-border bg-card p-2 text-left">{p.display_name}</th>)}</tr></thead><tbody>{participants.map(a=><tr key={a.id}><th className="sticky left-0 z-10 border border-border bg-card p-2 text-left">{a.display_name}</th>{participants.map(b=>{const allowed=map.get(`${a.id}:${b.id}`);return <td key={b.id} className="border border-border p-1 text-center">{a.id===b.id?<span className="text-slate-500">—</span>:<button title={`${a.display_name} can give to ${b.display_name}`} onClick={()=>setRule(a.id,b.id,allowed!==true)} className={`rounded px-2 py-1 ${allowed?'bg-green-500/20 text-green-200':'bg-red-500/20 text-red-200'}`}>{allowed?'Allowed':'Blocked'}</button>}</td>})}</tr>)}</tbody></table></div>}
