import {useEffect,useMemo,useState} from 'react';
import {User,UserAdmin,Participant,CompatibilityRule} from '../types/api';
import {api,del,patch,post} from '../lib/api';

type Section='admins'|'participants'|'compatibility'|'quarters';
type Invite={id:number;invitee_name:string;invitee_email?:string|null;created_by_name?:string|null;created_at:string;expires_at:string;status:string;invitation_url?:string;token?:string};

export function Settings({user}:{user:User}){
  const [section,setSection]=useState<Section>('participants');
  return <div className="space-y-6"><div><h1 className="text-3xl font-semibold">Settings</h1><p className="mt-1 text-slate-400">Simplified administration for participants, compatibility and quarterly distributions.</p></div>
    <div className="flex flex-wrap gap-2">{(['participants','compatibility','quarters','admins'] as Section[]).map(s=><button key={s} onClick={()=>setSection(s)} className={`rounded-xl px-4 py-2 text-sm capitalize ${section===s?'bg-indigo-500 text-white':'border border-border text-slate-300'}`}>{s}</button>)}</div>
    {section==='admins'&&<Admins current={user}/>} {section==='participants'&&<Participants/>} {section==='compatibility'&&<Compatibility/>} {section==='quarters'&&<p className="card p-6 text-slate-300">Quarter participant selection, validation, generation, preview and publishing lives on the Quarters page.</p>}
  </div>;
}

function Admins({current}:{current:User}){
 const[users,setUsers]=useState<UserAdmin[]>([]);const[invites,setInvites]=useState<Invite[]>([]);const[msg,setMsg]=useState('');const[created,setCreated]=useState<Invite|null>(null);const[invite,setInvite]=useState({invitee_name:'',invitee_email:'',expires_in_hours:168});const[edit,setEdit]=useState<Record<number,Partial<UserAdmin>&{password?:string}>>({});
 const isSuper=!!current.is_super_admin; const load=async()=>{setUsers(await api<UserAdmin[]>('/users')); if(isSuper)setInvites(await api<Invite[]>('/admin-invitations'))};useEffect(()=>{void load()},[]);
 async function save(u:UserAdmin){try{await patch(`/users/${u.id}`,edit[u.id]||{});setEdit(e=>{const n={...e};delete n[u.id];return n});setMsg('Administrator updated.');await load()}catch(e:any){setMsg(e.message)}}
 async function deactivate(u:UserAdmin){if(!confirm(`${u.is_active?'Deactivate':'Reactivate'} ${u.display_name}?`))return;try{await patch(`/users/${u.id}`,{is_active:!u.is_active});await load()}catch(e:any){setMsg(e.message)}}
 async function remove(u:UserAdmin){if(!confirm(`Delete ${u.display_name}? Historical records will be preserved and the account will be deactivated.`))return;try{await del(`/users/${u.id}`);await load()}catch(e:any){setMsg(e.message)}}
 async function createInvite(e:React.FormEvent){e.preventDefault();setMsg('');setCreated(null);try{const r=await post<Invite>('/admin-invitations',invite);setCreated(r);setInvite({invitee_name:'',invitee_email:'',expires_in_hours:168});await load()}catch(e:any){setMsg(e.message)}}
 async function revoke(i:Invite){if(!confirm(`Revoke invitation for ${i.invitee_name}?`))return;try{await del(`/admin-invitations/${i.id}`);await load()}catch(e:any){setMsg(e.message)}}
 const field=(u:UserAdmin,k:keyof UserAdmin)=>String((edit[u.id]?.[k]??u[k]??''));
 return <div className="space-y-6"><div className="card p-6"><h2 className="text-lg font-semibold">Administrators</h2><p className="mt-1 text-sm text-slate-400">Only administrator accounts log in. Participants do not need accounts.</p>{msg&&<p className="mt-3 text-red-300">{msg}</p>}<div className="mt-4 overflow-auto"><table className="w-full text-sm"><thead className="text-left text-slate-400"><tr><th className="p-2">Name</th><th>Username</th><th>Email</th><th>Role</th><th>Status</th><th>Last login</th><th/></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-t border-border align-top"><td className="p-2"><input disabled={!isSuper} value={field(u,'display_name')} onChange={e=>setEdit({...edit,[u.id]:{...edit[u.id],display_name:e.target.value}})} className="w-36 rounded bg-bg p-2"/></td><td><input disabled={!isSuper} value={field(u,'username')} onChange={e=>setEdit({...edit,[u.id]:{...edit[u.id],username:e.target.value}})} className="w-32 rounded bg-bg p-2"/></td><td><input disabled={!isSuper} value={field(u,'email')} onChange={e=>setEdit({...edit,[u.id]:{...edit[u.id],email:e.target.value}})} className="w-48 rounded bg-bg p-2"/></td><td><label><input disabled={!isSuper} type="checkbox" checked={!!(edit[u.id]?.is_super_admin??u.is_super_admin)} onChange={e=>setEdit({...edit,[u.id]:{...edit[u.id],is_super_admin:e.target.checked,is_admin:true}})}/> Main Admin</label><br/><label><input disabled={!isSuper} type="checkbox" checked={!!(edit[u.id]?.is_admin??u.is_admin)} onChange={e=>setEdit({...edit,[u.id]:{...edit[u.id],is_admin:e.target.checked}})}/> Admin</label></td><td>{u.is_active?'Active':'Inactive'}</td><td>{u.last_login_at?new Date(u.last_login_at).toLocaleString():'—'}</td><td className="space-x-2 whitespace-nowrap">{isSuper&&<><button onClick={()=>save(u)} className="rounded bg-indigo-500 px-3 py-1 text-xs">Save</button><button onClick={()=>deactivate(u)} className="rounded border border-border px-3 py-1 text-xs">{u.is_active?'Deactivate':'Reactivate'}</button><button onClick={()=>remove(u)} className="rounded border border-red-400 px-3 py-1 text-xs text-red-200">Delete</button></>}</td></tr>)}</tbody></table></div></div>
 {isSuper&&<div className="card p-6"><h2 className="text-lg font-semibold">Invitation links</h2><form onSubmit={createInvite} className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_140px_auto]"><input required value={invite.invitee_name} onChange={e=>setInvite({...invite,invitee_name:e.target.value})} placeholder="Invitee name" className="rounded bg-bg p-3"/><input type="email" value={invite.invitee_email} onChange={e=>setInvite({...invite,invitee_email:e.target.value})} placeholder="Optional email" className="rounded bg-bg p-3"/><input type="number" min={1} value={invite.expires_in_hours} onChange={e=>setInvite({...invite,expires_in_hours:Number(e.target.value)})} className="rounded bg-bg p-3"/><button className="rounded bg-teal-500 px-4 font-semibold">Create invite</button></form>{created&&<p className="mt-4 rounded bg-green-500/10 p-3 text-green-200">Invitation created. Copy now: <code>{location.origin}{created.invitation_url}</code> <button className="ml-2 underline" onClick={()=>navigator.clipboard?.writeText(`${location.origin}${created.invitation_url}`)}>Copy</button></p>}<table className="mt-4 w-full text-sm"><thead className="text-left text-slate-400"><tr><th className="p-2">Name</th><th>Email</th><th>Created by</th><th>Expires</th><th>Status</th><th/></tr></thead><tbody>{invites.map(i=><tr key={i.id} className="border-t border-border"><td className="p-2">{i.invitee_name}</td><td>{i.invitee_email||'—'}</td><td>{i.created_by_name||'—'}</td><td>{new Date(i.expires_at).toLocaleString()}</td><td>{i.status}</td><td>{i.status==='pending'&&<button onClick={()=>revoke(i)} className="rounded border border-red-400 px-3 py-1 text-xs text-red-200">Revoke</button>}</td></tr>)}</tbody></table></div>}
 </div>
}

function Participants(){
 const[items,setItems]=useState<Participant[]>([]);const[search,setSearch]=useState('');const[filter,setFilter]=useState('all');const[name,setName]=useState('');const[bulk,setBulk]=useState('');const[msg,setMsg]=useState('');const[edit,setEdit]=useState<Record<number,Partial<Participant>>>({});
 const load=async()=>setItems(await api<Participant[]>(`/participants?include_inactive=true${search?`&search=${encodeURIComponent(search)}`:''}`));useEffect(()=>{void load()},[search]);
 const visible=items.filter(p=>filter==='all'||(filter==='active'?p.is_active:!p.is_active));
 async function add(e:React.FormEvent){e.preventDefault();try{await post('/participants',{display_name:name});setName('');setMsg('Participant created.');await load()}catch(e:any){setMsg(e.message)}}
 async function addBulk(){try{const r=await post<any>('/participants/bulk',{names:bulk});setMsg(r.message||`${r.created_count||0} participants created`);if((r.created_count||0)>0)setBulk('');await load()}catch(e:any){setMsg(e.message)}}
 async function save(p:Participant){try{await patch(`/participants/${p.id}`,edit[p.id]||{});setEdit(e=>{const n={...e};delete n[p.id];return n});setMsg('Participant updated.');await load()}catch(e:any){setMsg(e.message)}}
 async function toggle(p:Participant){try{await (p.is_active?post(`/participants/${p.id}/deactivate`):post(`/participants/${p.id}/reactivate`));await load()}catch(e:any){setMsg(e.message)}}
 async function remove(p:Participant){if(!confirm(`Delete ${p.display_name}? Historical participants cannot be deleted and should be deactivated instead.`))return;try{await del(`/participants/${p.id}`);await load()}catch(e:any){setMsg(e.message)}}
 const val=(p:Participant,k:keyof Participant)=>String((edit[p.id]?.[k]??p[k]??''));
 return <div className="space-y-4"><div className="card p-6"><h2 className="text-lg font-semibold">Participant Management</h2><p className="mt-1 text-sm text-slate-400">Participants are distribution people only. No username, password, email or role is required.</p><form onSubmit={add} className="mt-4 flex gap-2"><input value={name} onChange={e=>setName(e.target.value)} required placeholder="Participant name" className="flex-1 rounded bg-bg p-3 text-sm"/><button className="rounded bg-indigo-500 px-4 font-semibold">Add participant</button></form><div className="mt-4 grid gap-3 md:grid-cols-[1fr_auto]"><textarea value={bulk} onChange={e=>setBulk(e.target.value)} placeholder={'Paste names, one per line\nAdam\nAlex\nBilly'} className="min-h-32 rounded bg-bg p-3 text-sm"/><button onClick={addBulk} disabled={!bulk.trim()} className="rounded bg-teal-500 px-4 font-semibold disabled:opacity-50">Bulk add</button></div>{msg&&<p className="mt-3 rounded bg-black/20 p-3 text-sm text-slate-200">{msg}</p>}</div><div className="card p-6"><div className="flex flex-wrap gap-2"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search participants" className="rounded bg-bg p-3 text-sm"/><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded bg-bg p-3 text-sm"><option value="all">All</option><option value="active">Active</option><option value="inactive">Inactive</option></select><span className="p-3 text-sm text-slate-400">{visible.length} shown / {items.length} total</span></div><div className="mt-4 overflow-auto"><table className="w-full text-sm"><thead className="text-left text-slate-400"><tr><th className="p-2">Name</th><th>Slug</th><th>Status</th><th>Current quarter</th><th>Public link</th><th/></tr></thead><tbody>{visible.map(p=><tr key={p.id} className="border-t border-border"><td className="p-2"><input value={val(p,'display_name')} onChange={e=>setEdit({...edit,[p.id]:{...edit[p.id],display_name:e.target.value}})} className="rounded bg-bg p-2"/></td><td><input value={val(p,'slug')} onChange={e=>setEdit({...edit,[p.id]:{...edit[p.id],slug:e.target.value}})} className="rounded bg-bg p-2"/></td><td>{p.is_active?'Active':'Inactive'}</td><td>{p.included_in_current_quarter?'Included':'Not included'}</td><td><a className="text-indigo-300 underline" href={`/tree/${p.slug}`} target="_blank">/tree/{p.slug}</a> <button onClick={()=>navigator.clipboard?.writeText(`${location.origin}/tree/${p.slug}`)} className="ml-2 rounded border border-border px-2 py-1 text-xs">Copy</button></td><td className="space-x-2 whitespace-nowrap"><button onClick={()=>save(p)} className="rounded bg-indigo-500 px-3 py-1 text-xs">Save</button><button onClick={()=>toggle(p)} className="rounded border border-border px-3 py-1 text-xs">{p.is_active?'Deactivate':'Reactivate'}</button><button onClick={()=>remove(p)} className="rounded border border-red-400 px-3 py-1 text-xs text-red-200">Delete</button></td></tr>)}</tbody></table></div></div></div>
}

function Compatibility(){const[participants,setParticipants]=useState<Participant[]>([]);const[rules,setRules]=useState<CompatibilityRule[]>([]);const[sel,setSel]=useState<number[]>([]);const[msg,setMsg]=useState('');const load=async()=>{setParticipants(await api<Participant[]>('/participants?include_inactive=false'));setRules(await api<CompatibilityRule[]>('/compatibility/rules'))};useEffect(()=>{void load()},[]);const map=useMemo(()=>new Map(rules.map(r=>[`${r.from_participant_id}:${r.to_participant_id}`,r.is_allowed])),[rules]);async function setRule(a:number,b:number,allowed:boolean){await api('/compatibility/rules',{method:'PUT',body:JSON.stringify({from_participant_id:a,to_participant_id:b,is_allowed:allowed,mutual:false})});await load()}async function bulk(path:string){await post(`/compatibility/${path}`,{from_participant_ids:sel,to_participant_ids:sel,is_allowed:path==='bulk-allow',mutual:true});setMsg(path==='bulk-allow'?'Selected group allowed.':'Selected group blocked.');await load()}return <div className="card overflow-auto p-6"><h2 className="text-lg font-semibold">Compatibility</h2><p className="mt-1 text-sm text-slate-400">Click cells to allow or block directed relationships. Compatibility is eligibility only; generation may use any valid subset.</p>{msg&&<p className="mt-3 text-sm text-slate-300">{msg}</p>}<div className="my-4 flex flex-wrap gap-2">{participants.map(p=><label key={p.id} className="rounded border border-border px-3 py-1 text-sm"><input type="checkbox" checked={sel.includes(p.id)} onChange={e=>setSel(e.target.checked?[...sel,p.id]:sel.filter(id=>id!==p.id))}/> {p.display_name}</label>)}<button onClick={()=>bulk('bulk-allow')} disabled={sel.length<2} className="rounded bg-teal-500 px-3 text-sm font-semibold disabled:opacity-50">Allow selected group</button><button onClick={()=>bulk('bulk-block')} disabled={sel.length<2} className="rounded border border-red-400 px-3 text-sm font-semibold text-red-200 disabled:opacity-50">Block selected group</button></div><table className="text-xs"><thead><tr><th className="sticky left-0 bg-card p-2">Participant</th>{participants.map(p=><th key={p.id} className="p-2 text-left">{p.display_name}</th>)}</tr></thead><tbody>{participants.map(a=><tr key={a.id}><th className="sticky left-0 bg-card p-2 text-left">{a.display_name}</th>{participants.map(b=>{const allowed=map.get(`${a.id}:${b.id}`);return <td key={b.id} className="p-1">{a.id===b.id?<span className="text-slate-500">—</span>:<button onClick={()=>setRule(a.id,b.id,allowed!==true)} className={`rounded px-2 py-1 ${allowed?'bg-green-500/20 text-green-200':'bg-red-500/20 text-red-200'}`}>{allowed?'Allowed':'Blocked'}</button>}</td>})}</tr>)}</tbody></table></div>}
